efs/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
]

portfolio/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'portfolio'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('customer/<int:pk>/portfolio/', views.portfolio, name='portfolio'),
    # urls for Customers
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('customer/create/', views.customer_new, name='customer_new'),
    url(r'^customers_json/', views.CustomerList.as_view()),
    # urls for Investments
    path('investment_list', views.investment_list, name='investment_list'),
    path('investment/<int:pk>/edit/', views.investment_edit, name='investment_edit'),
    path('investment/<int:pk>/delete/', views.investment_delete, name='investment_delete'),
    path('investment/create/', views.investment_new, name='investment_new'),
    # urls for Stocks
    path('stock_list', views.stock_list, name='stock_list'),
    path('stock/<int:pk>/edit/', views.stock_edit, name='stock_edit'),
    path('stock/<int:pk>/delete/', views.stock_delete, name='stock_delete'),
    path('stock/create/', views.stock_new, name='stock_new'),
    # urls for Mutual Funds
    path('mutual_fund_list', views.mutual_fund_list, name='mutual_fund_list'),
    path('mutual_fund/<int:pk>/edit/', views.mutual_fund_edit, name='mutual_fund_edit'),
    path('mutual_fund/<int:pk>/delete/', views.mutual_fund_delete, name='mutual_fund_delete'),
    path('mutual_fund/create/', views.mutual_fund_new, name='mutual_fund_new'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

portfolio/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import requests
from decimal import Decimal


# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    cust_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=200)
    cell_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_number)


class Investment(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='investments')
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    acquired_value = models.DecimalField(max_digits=10, decimal_places=2)
    acquired_date = models.DateField(default=timezone.now)
    recent_value = models.DecimalField(max_digits=10, decimal_places=2)
    recent_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.acquired_date = timezone.now()
        self.save()

    def updated(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def results_by_investment(self):
        return self.recent_value - self.acquired_value


class Stock(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='stocks')
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    shares = models.DecimalField(max_digits=10, decimal_places=1)
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def initial_stock_value(self):
        return self.shares * self.purchase_price

    def current_stock_price(self):
        symbol_f = str(self.symbol)
        main_api = 'https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol='
        api_key = '&apikey= JNO0VT6F5XU1HWZU'
        url = main_api + symbol_f + api_key
        json_data = requests.get(url).json()
        open_price = json_data.get('Global Quote', {}).get("05. price", self.purchase_price)
        share_value = open_price
        return share_value

    def current_stock_value(self):
        return round((Decimal(self.current_stock_price()) * Decimal(self.shares)), 3)


class MutualFund(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='mutual_funds')
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    shares = models.DecimalField(max_digits=10, decimal_places=1)
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def initial_mutual_fund_value(self):
        return self.shares * self.purchase_price

    def current_mutual_fund_price(self):
        mf_symbol_f = str(self.symbol)
        mf_main_api = 'https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol='
        mf_api_key = '&apikey=GOMG8YHN1JRNWXZO'
        mf_url = mf_main_api + mf_symbol_f + mf_api_key
        mf_json_data = requests.get(mf_url).json()
        mf_open_price = mf_json_data.get('Global Quote', {}).get("05. price", self.purchase_price)
        mf_share_value = mf_open_price
        return mf_share_value

    def current_mutual_fund_value(self):
        return round((Decimal(self.current_mutual_fund_price()) * Decimal(self.shares)), 3)

portfolio/forms.py
from django import forms
from .models import Customer, Investment, Stock, MutualFund


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)


class InvestmentForm(forms.ModelForm):
    class Meta:
        model = Investment
        fields = (
            'customer', 'category', 'description', 'acquired_value', 'acquired_date', 'recent_value', 'recent_date')


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date')


class MutualFundForm(forms.ModelForm):
    class Meta:
        model = MutualFund
        fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date')

portfolio/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.db.models import Sum
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomerSerializer

now = timezone.now()


def home(request):
    return render(request, 'portfolio/home.html',
                  {'portfolio': home})


@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/customer_list.html',
                  {'customers': customer})


@login_required
def customer_edit(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == "POST":
        # update
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.updated_date = timezone.now()
            customer.save()
            customer = Customer.objects.filter(created_date__lte=timezone.now())
            return render(request, 'portfolio/customer_list.html',
                          {'customers': customer})
    else:
        # edit
        form = CustomerForm(instance=customer)
    return render(request, 'portfolio/customer_edit.html', {'form': form})


@login_required
def customer_delete(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customer.delete()
    return redirect('portfolio:customer_list')


@login_required
def customer_new(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.created_date = timezone.now()
            customer.save()
            customers = Customer.objects.filter(created_date__lte=timezone.now())
            return render(request, 'portfolio/customer_list.html',
                          {'customers': customers})
    else:
        form = CustomerForm()
        # print("Else")
    return render(request, 'portfolio/customer_new.html', {'form': form})


@login_required
def investment_list(request):
    investment = Investment.objects.filter()
    return render(request, 'portfolio/investment_list.html',
                  {'investments': investment})


@login_required
def investment_edit(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    if request.method == "POST":
        # update
        form = InvestmentForm(request.POST, instance=investment)
        if form.is_valid():
            investment = form.save(commit=False)
            investment.recent_date = timezone.now()
            investment.save()
            investment = Investment.objects.filter()
            return render(request, 'portfolio/investment_list.html',
                          {'investments': investment})
    else:
        # edit
        form = InvestmentForm(instance=investment)
    return render(request, 'portfolio/investment_edit.html', {'form': form})


@login_required
def investment_delete(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    investment.delete()
    return redirect('portfolio:investment_list')


@login_required
def investment_new(request):
    if request.method == "POST":
        form = InvestmentForm(request.POST)
        if form.is_valid():
            investment = form.save(commit=False)
            investment.created_date = timezone.now()
            investment.save()
            investments = Investment.objects.filter()
            return render(request, 'portfolio/investment_list.html',
                          {'investments': investments})
    else:
        form = InvestmentForm()
        # print("Else")
    return render(request, 'portfolio/investment_new.html', {'form': form})


@login_required
def stock_list(request):
    stock = Stock.objects.filter()
    return render(request, 'portfolio/stock_list.html',
                  {'stocks': stock})


@login_required
def stock_edit(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    if request.method == "POST":
        # update
        form = StockForm(request.POST, instance=stock)
        if form.is_valid():
            stock = form.save(commit=False)
            stock.save()
            stock = Stock.objects.filter()
            return render(request, 'portfolio/stock_list.html',
                          {'stocks': stock})
    else:
        # edit
        form = StockForm(instance=stock)
    return render(request, 'portfolio/stock_edit.html', {'form': form})


@login_required
def stock_delete(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    stock.delete()
    return redirect('portfolio:stock_list')


@login_required
def stock_new(request):
    if request.method == "POST":
        form = StockForm(request.POST)
        if form.is_valid():
            stock = form.save(commit=False)
            stock.created_date = timezone.now()
            stock.save()
            stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
            return render(request, 'portfolio/stock_list.html',
                          {'stocks': stocks})
    else:
        form = StockForm()
        # print("Else")
    return render(request, 'portfolio/stock_new.html', {'form': form})


@login_required
def mutual_fund_list(request):
    mutual_fund = MutualFund.objects.filter()
    return render(request, 'portfolio/mutual_fund_list.html',
                  {'mutual_funds': mutual_fund})


@login_required
def mutual_fund_edit(request, pk):
    mutual_fund = get_object_or_404(MutualFund, pk=pk)
    if request.method == "POST":
        # update
        form = MutualFundForm(request.POST, instance=mutual_fund)
        if form.is_valid():
            mutual_fund = form.save(commit=False)
            mutual_fund.save()
            mutual_funds = MutualFund.objects.filter()
            return render(request, 'portfolio/mutual_fund_list.html',
                          {'mutual_funds': mutual_funds})
    else:
        # edit
        form = MutualFundForm(instance=mutual_fund)
    return render(request, 'portfolio/mutual_fund_edit.html', {'form': form})


@login_required
def mutual_fund_delete(request, pk):
    mutual_fund = get_object_or_404(MutualFund, pk=pk)
    mutual_fund.delete()
    return redirect('portfolio:mutual_fund_list')


@login_required
def mutual_fund_new(request):
    if request.method == "POST":
        form = MutualFundForm(request.POST)
        if form.is_valid():
            mutual_fund = form.save(commit=False)
            mutual_fund.created_date = timezone.now()
            mutual_fund.save()
            mutual_funds = MutualFund.objects.filter(purchase_date__lte=timezone.now())
            return render(request, 'portfolio/mutual_fund_list.html',
                          {'mutual_funds': mutual_funds})
    else:
        form = MutualFundForm()
        # print("Else")
    return render(request, 'portfolio/mutual_fund_new.html', {'form': form})


@login_required
def portfolio(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    investments = Investment.objects.filter(customer=pk)
    stocks = Stock.objects.filter(customer=pk)
    mutual_funds = MutualFund.objects.filter(customer=pk)
    sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
    sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
    # overall_investment_results = sum_recent_value-sum_acquired_value
    # Initialize the value of the stocks
    sum_current_stocks_value = 0
    sum_of_initial_stock_value = 0
    sum_current_mutual_fund_value = 0
    sum_initial_mutual_fund_value = 0

    # Loop through each stock and add the value to the total
    for stock in stocks:
        sum_current_stocks_value += stock.current_stock_value()
        sum_of_initial_stock_value += stock.initial_stock_value()

    for mutual_fund in mutual_funds:
        sum_current_mutual_fund_value += mutual_fund.current_mutual_fund_value()
        sum_initial_mutual_fund_value += mutual_fund.initial_mutual_fund_value()

    sum_recent_investments = sum_recent_value.get('recent_value__sum')
    sum_acquired_investments = sum_acquired_value.get('acquired_value__sum')

    portfolio_initial_total = sum_of_initial_stock_value + sum_initial_mutual_fund_value + sum_acquired_investments
    portfolio_current_total = sum_current_stocks_value + sum_current_mutual_fund_value + sum_recent_investments

    return render(request, 'portfolio/portfolio.html', {'customers': customers,
                                                        'investments': investments,
                                                        'stocks': stocks,
                                                        'sum_acquired_value': sum_acquired_value,
                                                        'sum_recent_value': sum_recent_value,
                                                        'sum_current_stocks_value': sum_current_stocks_value,
                                                        'sum_of_initial_stock_value': sum_of_initial_stock_value,
                                                        'portfolio_initial_total': portfolio_initial_total,
                                                        'portfolio_current_total': portfolio_current_total,
                                                        'sum_recent_investments': sum_recent_investments,
                                                        'sum_acquired_investments': sum_acquired_investments,
                                                        'sum_current_mutual_fund_value': sum_current_mutual_fund_value,

portfolio/templates/portfolio/customer_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Edit Customer</h1>
<form method="POST" class="customer-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-default">Update</button>
</form>
{% endblock %}

portfolio/templates/portfolio/customer_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Eagle Financial</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
<style>
    body {
        background-color: beige;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    Eagle Financial Services, your Midwest Financial Services Partner.
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <h2 style="padding-left: 15Px">Customer Information</h2>
</div>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer Number</th>
            <th>Name</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th>Primary Email</th>
            <th>Cell Phone</th>
            <th colspan="3">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for customer in customers %}
        <tr>
            <td>{{ customer.cust_number }}</td>
            <td>{{ customer.name }}</td>
            <td>{{ customer.address }}</td>
            <td>{{ customer.city }}</td>
            <td>{{ customer.state }}</td>
            <td>{{ customer.zipcode }}</td>
            <td>{{ customer.email }}</td>
            <td>{{ customer.cell_phone }}</td>
            <td>
                <a href="{% url 'portfolio:customer_edit' pk=customer.pk %}" class="btn btn-warning">Edit</a>
            </td>
            <td><a href="{% url 'portfolio:customer_delete' pk=customer.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
            </td>
            <td>
                <a href="{% url 'portfolio:portfolio' pk=customer.pk %}" class="btn btn-primary">Portfolio</a>
            </td>

        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row">
        <a href="{% url 'portfolio:customer_new' %}" class="row">
            <span class="btn btn-primary">Add Customer</span>
        </a>
    </div>
</div>
</body>
</html>
{% endblock %}

portfolio/templates/portfolio/customer_new.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Add a New Customer</h1>
<form method="POST" class="customer-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

portfolio/templates/portfolio/investment_delete.html
{% extends 'portfolio/base.html' %}
{% block body_block %}
<h1>Delete {{ investment.category }}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'portfolio:home' pk=investment.customer.cust_number %} ">Cancel</a>
</form>
{% endblock %}

portfolio/templates/portfolio/investment_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Edit Investment</h1>
<form method="POST" class="investment-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-default">Update</button>
</form>
{% endblock %}

portfolio/templates/portfolio/investment_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Eagle Financial</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
<style>
    body {
        background-color: beige;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    Eagle Financial Services, your Midwest Financial Services Partner.
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <h2 style="padding-left: 15Px">Investment Information</h2>
</div>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer Number</th>
            <th>Customer Name</th>
            <th>Category</th>
            <th>Description</th>
            <th>Acquired Value</th>
            <th>Acquired Date</th>
            <th>Recent Value</th>
            <th>Recent Date</th>
            <th colspan="2">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for investment in investments %}
        <tr>
            <td>{{ investment.customer.cust_number }}</td>
            <td>{{ investment.customer.name }}</td>
            <td>{{ investment.category }}</td>
            <td>{{ investment.description }}</td>
            <td>{{ investment.acquired_value }}</td>
            <td>{{ investment.acquired_date }}</td>
            <td>{{ investment.recent_value }}</td>
            <td>{{ investment.recent_date }}</td>
            <td>
                <a href="{% url 'portfolio:investment_edit' pk=investment.pk %}" class="btn btn-warning">Edit</a>
            </td>
            <td><a href="{% url 'portfolio:investment_delete' pk=investment.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row">
        <a href="{% url 'portfolio:investment_new' %}" class="row">
            <span class="btn btn-primary">Add Investment</span>
        </a>
    </div>
</div>
</body>
</html>
{% endblock %}

portfolio/templates/portfolio/mutual_fund_delete.html
{% extends 'portfolio/base.html' %}
{% block body_block %}
<h1>Delete {{ mutual_fund.name }}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'portfolio:home' pk=mutual_fund.customer.cust_number %} ">Cancel</a>
</form>
{% endblock %}

portfolio/templates/portfolio/mutual_fund_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Edit Mutual Fund</h1>
<form method="POST" class="mutual-fund-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-default">Update</button>
</form>
{% endblock %}

portfolio/templates/portfolio/mutual_fund_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Eagle Financial</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
<style>
    body {
        background-color: beige;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    Eagle Financial Services, your Midwest Financial Services Partner.
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <h2 style="padding-left: 15Px">Mutual Fund Information</h2>
</div>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer Number</th>
            <th>Customer Name</th>
            <th>Symbol</th>
            <th>Name</th>
            <th>Shares</th>
            <th>Purchase Price</th>
            <th>Purchase Date</th>
            <th colspan="2">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for mutual_fund in mutual_funds %}
        <tr>
            <td>{{ mutual_fund.customer.cust_number }}</td>
            <td>{{ mutual_fund.customer.name }}</td>
            <td>{{ mutual_fund.symbol }}</td>
            <td>{{ mutual_fund.name}}</td>
            <td>{{ mutual_fund.shares }}</td>
            <td>{{ mutual_fund.purchase_price }}</td>
            <td>{{ mutual_fund.purchase_date }}</td>
            <td><a href="{% url 'portfolio:mutual_fund_edit' pk=mutual_fund.pk %}" class="btn btn-warning">Edit</a></td>
            <td><a href="{% url 'portfolio:mutual_fund_delete' pk=mutual_fund.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row">
        <a href="{% url 'portfolio:mutual_fund_new' %}" class="row">
            <span class="btn btn-primary">Add Mutual Fund</span>
        </a>
    </div>
</div>
</body>
</html>
{% endblock %}

portfolio/templates/portfolio/mutual_fund_new.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Add a New Mutual Fund</h1>
<form method="POST" class="mutual-fund-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}

portfolio/templates/portfolio/stock_edit.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Edit Stock</h1>
<form method="POST" class="stock-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-default">Update</button>
</form>
{% endblock %}

portfolio/templates/portfolio/stock_list.html
{% extends 'portfolio/base.html' %}
{% block content %}

<html>
<head>
    <meta charset="UTF-8">
    <title>Eagle Financial</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
<style>
    body {
        background-color: beige;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome!</div>
                <div class="panel-body">
                    Eagle Financial Services, your Midwest Financial Services Partner.
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <h2 style="padding-left: 15Px">Stock Information</h2>
</div>
<div>
    <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr class="bg-info">
            <th>Customer Number</th>
            <th>Customer Name</th>
            <th>Symbol</th>
            <th>Name</th>
            <th>Shares</th>
            <th>Purchase Price</th>
            <th>Purchase Date</th>
            <th colspan="2">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for stock in stocks %}
        <tr>
            <td>{{ stock.customer.cust_number }}</td>
            <td>{{ stock.customer.name }}</td>
            <td>{{ stock.symbol }}</td>
            <td>{{ stock.name}}</td>
            <td>{{ stock.shares }}</td>
            <td>{{ stock.purchase_price }}</td>
            <td>{{ stock.purchase_date }}</td>
            <td><a href="{% url 'portfolio:stock_edit' pk=stock.pk %}" class="btn btn-warning">Edit</a></td>
            <td><a href="{% url 'portfolio:stock_delete' pk=stock.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row">
        <a href="{% url 'portfolio:stock_new' %}" class="row">
            <span class="btn btn-primary">Add Stock</span>
        </a>
    </div>
</div>
</body>
</html>
{% endblock %}

portfolio/templates/portfolio/stock_new.html
{% extends 'portfolio/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Add a New Stock</h1>
<form method="POST" class="stock-form">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}